version: "3"
services:
  haproxy:
    container_name: reverse-proxy
    image: ridi/haproxy
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker-entrypoint.sh:/app/docker-entrypoint.sh:ro
      - ./docker-gen.cfg:/app/docker-gen.cfg:ro
      - ./haproxy.tmpl:/app/haproxy.tmpl:ro
      - ./vhosts.cfg:/app/vhosts.cfg:ro
      - ./ssl:/ssl:ro
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  dnsmasq:
    image: andyshinn/dnsmasq
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    environment:
      - IP_ADDR
    volumes:
      - ./dnsmasq-entrypoint.sh:/docker-entrypoint.sh:ro
      - ./vhosts.cfg:/vhosts.cfg:ro
    entrypoint: [
      "/bin/sh",
      "-c",
      "/docker-entrypoint.sh"
    ]