version: "3"
services:
  haproxy:
    image: ridi/haproxy
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CAROOT
    volumes:
      - ${CAROOT}:/usr/local/share/ca-certificates:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker-entrypoint.sh:/app/docker-entrypoint.sh:ro
      - ./docker-gen.cfg:/app/docker-gen.cfg:ro
      - ./haproxy.tmpl:/app/haproxy.tmpl:ro
      - ./vhosts.cfg:/app/vhosts.cfg:ro
      - ./ssl:/ssl:ro
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  dnsmasq:
    image: ridi/dnsmasq
    build: dnsmasq
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    environment:
      - IP_ADDR
    command: [
      "dnsmasq",
      "-k",
      "-h",
      "--address=/.local.ridi.io/.pay.local.ridi.io/${IP_ADDR:-127.0.0.1}"
    ]